apiVersion: v1
data:
  nginx.conf: "worker_processes 1;\nerror_log /dev/stderr info;\npid /tmp/nginx.pid;\n\
    events { worker_connections 256; }\nhttp {\n  access_log /dev/stdout;\n  server\
    \ {\n    listen 8080;\n    location / {\n      proxy_pass https://logging-loki-gateway-http.openshift-logging.svc.cluster.local:8080;\n\
    \      proxy_ssl_verify off;\n      proxy_set_header Host logging-loki-gateway-http.openshift-logging.svc.cluster.local;\n\
    \      proxy_set_header Authorization $http_authorization;\n      proxy_set_header\
    \ X-Forwarded-For $proxy_add_x_forwarded_for;\n      proxy_read_timeout 60s;\n\
    \      proxy_send_timeout 60s;\n    }\n  }\n}\n"
kind: ConfigMap
metadata:
  name: loki-proxy-config
  namespace: perses-dev
